### ISSUE TITLE
Co-relation between name_organization, name_taxonomic, summary with other name fields. 

### ISSUE THREAD

**Issue by mit2nil** [american-art/ima#11]
Hi,

I am not sure how to model name_organization, name_taxonomic and summary fields in aac-actors.json. I ran simple test script comparing values of name_full field and name_organization attribute and most of the values in name_organizaion are either same as name_full field or blank. 

- Nilay Chheda

**Comment by workergnome** [comment]
I think we need more information about what those fields are—they _sound_ like they are there because of a difference in the internal model between organizations and people, but I don't know for sure.

@IllyaMoskvin, do you have any insight?

**Comment by IllyaMoskvin** [comment]
`name_taxonomic` refers to the name as it was found in ULAN or more likely, our lexicon, which is derived from the Getty Vocabularies. `name_organization` is set only for organizations (i.e. `E40 Legal Body`). David is correct: if the actor is not an organization, `name_organization` will be null. `name_full` is a convenience field derived from `name_last` and `name_first`.

I'm glad to hear that you ran a script to compare `name_full` and `name_organization`. I believe that if the two are the same, `name_organization` is the canonical one. Also, if `name_full` is null, `name_organization` should be set, indicating an organization.

I unfortunately do not have a way to manually fix the data currently for any organizations that (erroneously) do not have `name_organization` set, but do have `name_full` set. I don't know if any such actors exist.

**Comment by SamiNorling** [comment]
Wanted to chime in on this one now that I am completing my review of our mappings and data in Browse, and since this issue is still open.

The current mapping, which uses the value of name_full as rdf:value of E38_Actor_Appellation2 works well with our data--name_full is pretty consistently used and is the best version of a creator name of the available name-related fields for each creator.

**Comment by SamiNorling** [comment]
Current mapping which utilizes name_full for rdf:value of each actor name, regardless if individual or organization, is good. With our data refresh, I am cleaning up the data so that this field is consistently used. This will also resolve the issue @workergnome mentioned at AAC meeting of many actors having NULL names (problem became apparent when looking at our 100 sample actors in Browse).

I suggest this issue be closed.
