### ISSUE TITLE
Birth place and Death Place appear to be blank.

### ISSUE THREAD

**Issue by workergnome** [american-art/ima#17]
See, for example: http://data.americanartcollaborative.org/page/ima/actor/id/1730/birth

There is a place entity: http://data.americanartcollaborative.org/page/ima/actor/id/1730/birth/place, but it has no values.

**Comment by IllyaMoskvin** [comment]
Hmm... It seems like it's a data quality problem present in the original JSON data, i.e. the data we pulled from our collections management system. It also seems like the data was processed into the triplestore correctly, e.g. compare:

http://data.americanartcollaborative.org/page/ima/actor/id/3203/birth/place

...with the original JSON object, found right above ID 1730:

https://raw.githubusercontent.com/american-art/ima/master/aac-actors/aac-actors.json

I suspect that ID 1730 might have been left blank because the record is incomplete, i.e. the registrar or whoever was responsible for data entry never got to verifying that information. I'm guessing the `Death Place` field was also set to `null` if the actor had not died yet. I understand that this can introduce ambiguity between incomplete information and living status. Not sure how to resolve that...

Question: what is the semantic difference between specifying a property as blank, and not specifying that property at all? Is there a distinction between `blank` and `null` as there is in relational databases? Would omitting a property result in the equivalent of a `null` return, when an attempt is made to access that property?

**Comment by workergnome** [comment]
Linked data is Open World, which means failing to emit a property means that it is unknown, not false or null.  

The appropriate thing to do here is to not emit anything, to capture the not-knownness of the data. By emitting this property, but without values, what you're stating is that he died in a location, but that location has no known properties.  While this can be useful, in this case it seems semantically identical to leaving it out.

**Comment by bsnikhila** [comment]
Removed the URI where there is no data.
